### ISSUE TITLE
滑动报错

### ISSUE THREAD

**Issue by beijing-java** [czy1121/bannerview#4]
轮播图只有一张图片的时候，滑动崩溃。
10-07 14:12:50.450 4493-4493/com.ia36.onecreate D/Error: ERR: exClass=java.lang.StackOverflowError
10-07 14:12:50.450 4493-4493/com.ia36.onecreate D/Error: ERR: exMsg=stack size 8MB
10-07 14:12:50.450 4493-4493/com.ia36.onecreate D/Error: ERR: file=LoopViewPager.java
10-07 14:12:50.450 4493-4493/com.ia36.onecreate D/Error: ERR: class=ezy.ui.view.LoopViewPager$InnerLoopAdapter
10-07 14:12:50.450 4493-4493/com.ia36.onecreate D/Error: ERR: method=getCount line=225
10-07 14:12:50.460 4493-4493/com.ia36.onecreate D/Error: ERR: stack=java.lang.StackOverflowError: stack size 8MB

**Comment by czy1121** [comment]
这个问题1.0.2应该已经修复了，可以试试看
